name: Generate Monthly Bills

on:
  # Agenda: Roda todo dia 1º do mês às 03:00 UTC (meia-noite no horário de Brasília - ajuste se necessário)
  schedule:
    - cron: '0 3 1 * *'
  # Permite rodar manualmente pela interface do GitHub Actions
  workflow_dispatch:

jobs:
  generate_bills:
    runs-on: ubuntu-latest # Usa uma máquina virtual Linux padrão do GitHub

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura o ambiente Python (use a mesma versão da sua API)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # <-- Verifique se é a mesma versão do seu requirements.txt/Render

      # 3. Instala as dependências necessárias para o script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Instala TUDO do requirements.txt principal

      # 4. Executa o script de geração de mensalidades
      - name: Run monthly billing script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} # Injeta o Secret na variável de ambiente
        run: python generate_monthly_bills.py